// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-formules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_formules_default = defineTool({
  name: "list_formules",
  title: "Lister les formules AssurDignit\xE9",
  description: "Retourne les formules d'assurance obs\xE8ques AssurDignit\xE9 (SONAM Vie): A Dignit\xE9 Simple, B Serein, C Prestige, D Excellence.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const formules = [
      {
        code: "A",
        nom: "Dignit\xE9 Simple",
        capital_fcfa: 15e5,
        cible: "Budget ma\xEEtris\xE9, couverture essentielle"
      },
      {
        code: "B",
        nom: "Serein",
        capital_fcfa: 2e6,
        cible: "\xC9quilibre couverture / prime"
      },
      {
        code: "C",
        nom: "Prestige",
        capital_fcfa: 3e6,
        cible: "Prestations \xE9largies, famille"
      },
      {
        code: "D",
        nom: "Excellence",
        capital_fcfa: 5e6,
        cible: "Couverture maximale \u2014 diaspora, prestations premium, rapatriement"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(formules, null, 2) }],
      structuredContent: { formules }
    };
  }
});

// src/lib/mcp/tools/contact-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact_info_default = defineTool2({
  name: "contact_info",
  title: "Coordonn\xE9es AssurDignit\xE9",
  description: "Retourne les coordonn\xE9es commerciales SONAM Vie / AssurDignit\xE9 (t\xE9l\xE9phones, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      marque: "AssurDignit\xE9",
      porteur_de_risque: "SONAM Vie",
      concepteur: "AIF SARL",
      telephones: ["+225 27 20 31 71 82", "+225 05 95 45 21 65"],
      email: "servicecommercialsonamvie@sonam.ci",
      site: "https://sonam-assurdignite-beta.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/tools/simuler-prime.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var CAPITAUX = {
  A: 15e5,
  B: 2e6,
  C: 3e6,
  D: 5e6
};
var simuler_prime_default = defineTool3({
  name: "simuler_prime",
  title: "Simuler une prime annuelle",
  description: "Estimation indicative de la prime annuelle AssurDignit\xE9 selon la formule (A/B/C/D) et l'\xE2ge de l'assur\xE9 principal (18-64 ans). Paiement annuel. Une ristourne de 30% de la prime de l'assur\xE9 principal est restitu\xE9e si aucun sinistre n'est survenu sur les 3 premi\xE8res ann\xE9es. R\xE9sultat non contractuel.",
  inputSchema: {
    formule: z.enum(["A", "B", "C", "D"]).describe("Code formule: A, B, C ou D"),
    age: z.number().int().min(18).max(64).describe("\xC2ge de l'assur\xE9 principal (18-64 ans)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ formule, age }) => {
    const capital = CAPITAUX[formule];
    const tauxBase = 8e-3 + Math.max(0, age - 30) * 4e-4;
    const primeAnnuelle = Math.round(capital * tauxBase / 100) * 100;
    const periodicites = {
      annuelle: primeAnnuelle,
      annuelle_prime: primeAnnuelle + 2500,
      semestrielle: Math.round(primeAnnuelle * 0.51 + 1500),
      trimestrielle: Math.round(primeAnnuelle * 0.26 + 1e3),
      mensuelle: Math.round(primeAnnuelle * 0.09 + 500)
    };
    const result = {
      formule,
      capital_fcfa: capital,
      couverture: "70% prestations en nature + 30% capital esp\xE8ces",
      age,
      prime_annuelle_indicative_fcfa: primeAnnuelle,
      periodicites_fcfa: periodicites,
      ristourne: "30% de la prime de l'assur\xE9 principal restitu\xE9e si aucun sinistre sur 3 ans",
      limites_age: { principal: "18-64", conjoint: "18-64", enfants: "0-21", ascendants: "0-89" },
      note: "Estimation non contractuelle. Tarification d\xE9finitive apr\xE8s KYC et adh\xE9sion."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "assurdignite-mcp",
  title: "AssurDignit\xE9 MCP",
  version: "0.1.0",
  instructions: "Outils publics AssurDignit\xE9 (SONAM Vie): consulter les formules d'assurance obs\xE8ques, obtenir les coordonn\xE9es commerciales, et simuler une prime annuelle indicative.",
  tools: [list_formules_default, contact_info_default, simuler_prime_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
